### ISSUE TITLE
[oefening04] gebruik van grid ipv. flex?

### ISSUE THREAD

**Issue by milvld** [Web-Development-I/09SOL-LayoutResponsive#2]
Bij het aanpakken van de brede lay-out, had ik zelf spontaan grid gebruikt ipv. flex (oplossing hieronder).

Biedt het een hier een duidelijk voordeel tegenover het andere? Visueel ziet het er alleszins hetzelfde uit.

```css
body {
  font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
  margin: 0px auto;
  padding: 1rem;
  max-width: 1200px;
}

h1 {
  text-align: center;
  font-weight: normal;
  color: rgb(67, 173, 235);
}

img {
  max-width: 100%;
}

main {
  display: block grid;
  gap: 1em;
  grid-template-columns: 100%;
}

article {
  padding: 0.5rem;
  border: 2px solid lightskyblue;
}

@media screen and (min-width: 700px) {
  h1 {
    font-size: 3.5em;
    color: mediumpurple;
  }

  article {
    border: 2px solid mediumpurple;
    display: block grid;
    grid-template-columns: 45% 53%;
    column-gap: 2%;
    align-items: center;
  }

  article div.event-image {
    grid-column: 1 / 2;
  }

  article div.event-txt {
    grid-column: 2;
  }
}

```
