### ISSUE TITLE
[oefening05-stap3-contact.html] probleem mbt. nesting dan <div> elementen

### ISSUE THREAD

**Issue by milvld** [Web-Development-I/09SOL-LayoutResponsive#4]
Wanneer ik de contact.html uit oefening 5 probeer te valideren, krijg ik de error `No p element in scope but a p end tag seen. ([From line 118, column 13; to line 118, column 16](https://validator.w3.org/nu/#l118c16))` (report normaliter [hier](https://validator.w3.org/nu/#l118c16) beschikbaar). Ik zie online ook dat het nesten van `<div>` elementen in `<p>` elementen blijkbaar wat gecontesteerd is (bv. [hier](https://stackoverflow.com/questions/4291467/nesting-block-level-elements-inside-the-p-tag-right-or-wrong)).

Zou het kunnen dat de `<div>` elementen met de radio buttons beter in een `<div>` genest worden? Op die manier kan je de radio buttons samen nemen als grid met 2 kolommen bv. en ze mooi naast elkaar positioneren, zoals ik hieronder deed:

```css
@import url(normalize.css);
@import url("https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,700;1,400&display=swap");

* {
  box-sizing: border-box;
}

body {
  font-family: "Roboto", sans-serif;
  color: #111;
  background-color: #525252;
}

h1 {
  margin-top: 0px;
  padding-top: 10px;
}

p,
li {
  line-height: 1.5;
}

nav {
  background-color: #393939;
}

footer {
  background-color: #ed1c24;
  color: white;
}

header,
main {
  background-color: #fff;
}

img {
  max-width: 100%;
}

a {
  color: #ed1c24;
  text-decoration: none;
}

a:hover {
  text-decoration: underline;
}

/* Navigatiebalk*/
/* **************/
nav {
  font-size: 1.2em;
}

nav ul {
  list-style-type: none;
}

nav a {
  color: white;
}

nav .current {
  color: #ed1c24;
  text-decoration: none;
}

header,
main,
footer {
  padding-left: 15px;
  padding-right: 15px;
}

header {
  padding-top: 10px;
  padding-bottom: 10px;
}

footer p {
  margin-top: 0.5em;
  margin-bottom: 0.5em;
}

.container {
  max-width: 960px;
  margin: 0 auto;
  background-color: white;
}

table {
  border-collapse: collapse;
}

th,
td {
  border: 1px solid #424242;
  padding: 0.2rem;
}

tr:first-child th {
  background-color: #424242;
  color: white;
}

td {
  text-align: center;
}

input[type="submit"] {
  font-size: 1.2em;
  background-color: #424242;
  color: white;
}

/* responsive nav */
nav ul {
  padding: 0;
  display: block flex;
  flex-wrap: wrap;
}

nav ul li {
  flex: 1 1 50%;
  padding: 1rem 0.3rem;
}

nav ul li:first-of-type,
nav ul li:nth-of-type(3) {
  text-align: right;
}

input,
select,
textarea {
  display: block;
}

.radios input {
  display: inline;
}

/* breakpoints */
@media screen and (min-width: 600px) {
  nav ul {
    justify-content: space-around;
  }

  nav ul li {
    flex: 0 0 auto;
    padding: 0.7rem 1rem;
  }

  main#contact-page {
    display: block grid;
    justify-items: start;
    grid-template-areas:
      "adres contact"
      "afspraak afspraak";
  }

  main#contact-page div.adres {
    grid-area: adres;
  }

  main#contact-page div.opening {
    grid-area: contact;
  }

  main#contact-page div.afspraak {
    grid-area: afspraak;
  }

  main#contact-page div.afspraak form p {
    display: block flex;
    flex-wrap: wrap;
    column-gap: 10px;
    row-gap: 10px;
  }

  main#contact-page div.afspraak form > div {
    display: block grid;
    grid-template-areas: "button1 button2";
    column-gap: 10px;
    justify-content: start;
  }

  main#contact-page div.radios:nth-child(1) {
    grid-area: button1;
  }

  main#contact-page div.radios:nth-child(2) {
    grid-area: button2;
  }

  main#contact-page div.afspraak form p:nth-last-child(2) {
    display: block;
  }
}

```
