### ISSUE TITLE
 [oefening05-stap3] flex vs. grid vs. alternatieven

### ISSUE THREAD

**Issue by milvld** [Web-Development-I/09SOL-LayoutResponsive#5]
Bij dit stuk van de oefening (en in het algemeen) twijfelde ik tussen het toepassen van grid, flex, een combinatie van de twee of alternatieven (bv. met `display: inline`, zoals in de voorbeeldoplossing). Is er hierbij een algemene regel, of is dit puur gevoel? 

Ik heb hieronder mijn twee alternatieve oplossing geplaatst voor dit stuk van de oefening. Ik ga hierbij wel uit van een omringende `<div>` rond de radio buttons (zie issue #4).

Ik denk dat ik vooral wat handvaten zoek rond wanneer wat toepassen.

## oplossing met combinatie van voornamelijk flex en een beetje grid

Deze oogt visueel hetzelfde als het resultaat van de voorbeeldoplossing, maar dan zonder `display: inline` (ik had dit vermeden omdat ik ergens eerder in de slides had gezien dat dit tegenwoordig minder gebruikt wordt ten voordele van flex en grid, dus ik verwachtte dit niet als oplossing).

Het intrigerende hierbij vind ik vooral dat de voorbeeldoplossing volledig gebruikmaakt van grid vs. mijn quasi volledig gebruik van flex.

```css
@import url(normalize.css);
@import url("https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,700;1,400&display=swap");

* {
  box-sizing: border-box;
}

body {
  font-family: "Roboto", sans-serif;
  color: #111;
  background-color: #525252;
}

h1 {
  margin-top: 0px;
  padding-top: 10px;
}

p,
li {
  line-height: 1.5;
}

nav {
  background-color: #393939;
}

footer {
  background-color: #ed1c24;
  color: white;
}

header,
main {
  background-color: #fff;
}

img {
  max-width: 100%;
}

a {
  color: #ed1c24;
  text-decoration: none;
}

a:hover {
  text-decoration: underline;
}

/* Navigatiebalk*/
/* **************/
nav {
  font-size: 1.2em;
}

nav ul {
  list-style-type: none;
}

nav a {
  color: white;
}

nav .current {
  color: #ed1c24;
  text-decoration: none;
}

header,
main,
footer {
  padding-left: 15px;
  padding-right: 15px;
}

header {
  padding-top: 10px;
  padding-bottom: 10px;
}

footer p {
  margin-top: 0.5em;
  margin-bottom: 0.5em;
}

.container {
  max-width: 960px;
  margin: 0 auto;
  background-color: white;
}

table {
  border-collapse: collapse;
}

th,
td {
  border: 1px solid #424242;
  padding: 0.2rem;
}

tr:first-child th {
  background-color: #424242;
  color: white;
}

td {
  text-align: center;
}

input[type="submit"] {
  font-size: 1.2em;
  background-color: #424242;
  color: white;
}

/* responsive nav */
nav ul {
  padding: 0;
  display: block flex;
  flex-wrap: wrap;
}

nav ul li {
  flex: 1 1 50%;
  padding: 1rem 0.3rem;
}

nav ul li:first-of-type,
nav ul li:nth-of-type(3) {
  text-align: right;
}

input,
select,
textarea {
  display: block;
}

.radios input {
  display: inline;
}

/* breakpoints */
@media screen and (min-width: 600px) {
  nav ul {
    justify-content: space-around;
  }

  nav ul li {
    flex: 0 0 auto;
    padding: 0.7rem 1rem;
  }

  /* contact page */

  main#contact-page {
    display: block grid;
    justify-items: start;
    grid-template-areas:
      "adres contact"
      "afspraak afspraak";
  }

  main#contact-page div.adres {
    grid-area: adres;
  }

  main#contact-page div.opening {
    grid-area: contact;
  }

  main#contact-page div.afspraak {
    grid-area: afspraak;
  }

  /* contact page form met flex */

  main#contact-page div.afspraak form p {
    display: block flex;
    flex-wrap: wrap;
    column-gap: 10px;
    row-gap: 10px;
  }

  main#contact-page div.afspraak form > div {
    display: block grid;
    grid-template-areas: "button1 button2";
    column-gap: 10px;
    justify-content: start;
  }

  main#contact-page div.radios:nth-child(1) {
    grid-area: button1;
  }

  main#contact-page div.radios:nth-child(2) {
    grid-area: button2;
  }

  main#contact-page div.afspraak form p:nth-last-child(2) {
    display: block;
  }

}

```

## oplossing met zuiver grid

Hoewel deze oplossing niet 100% overeenkomt met de gevraagde lay-out in de opgave, vind ik het alsnog een mogelijke kandidaat omdat deze zeer overzichtelijk oogt. Daarnaast is de code ook iets leesbaarder vind ik zelf; doordat het zuiver gridgebaseerd is, is het gewoon een relatief eenvoudige oplijsting van de kolommen met de relevante CSS-selectors

```css
@import url(normalize.css);
@import url("https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,700;1,400&display=swap");

* {
  box-sizing: border-box;
}

body {
  font-family: "Roboto", sans-serif;
  color: #111;
  background-color: #525252;
}

h1 {
  margin-top: 0px;
  padding-top: 10px;
}

p,
li {
  line-height: 1.5;
}

nav {
  background-color: #393939;
}

footer {
  background-color: #ed1c24;
  color: white;
}

header,
main {
  background-color: #fff;
}

img {
  max-width: 100%;
}

a {
  color: #ed1c24;
  text-decoration: none;
}

a:hover {
  text-decoration: underline;
}

/* Navigatiebalk*/
/* **************/
nav {
  font-size: 1.2em;
}

nav ul {
  list-style-type: none;
}

nav a {
  color: white;
}

nav .current {
  color: #ed1c24;
  text-decoration: none;
}

header,
main,
footer {
  padding-left: 15px;
  padding-right: 15px;
}

header {
  padding-top: 10px;
  padding-bottom: 10px;
}

footer p {
  margin-top: 0.5em;
  margin-bottom: 0.5em;
}

.container {
  max-width: 960px;
  margin: 0 auto;
  background-color: white;
}

table {
  border-collapse: collapse;
}

th,
td {
  border: 1px solid #424242;
  padding: 0.2rem;
}

tr:first-child th {
  background-color: #424242;
  color: white;
}

td {
  text-align: center;
}

input[type="submit"] {
  font-size: 1.2em;
  background-color: #424242;
  color: white;
}

/* responsive nav */
nav ul {
  padding: 0;
  display: block flex;
  flex-wrap: wrap;
}

nav ul li {
  flex: 1 1 50%;
  padding: 1rem 0.3rem;
}

nav ul li:first-of-type,
nav ul li:nth-of-type(3) {
  text-align: right;
}

input,
select,
textarea {
  display: block;
}

.radios input {
  display: inline;
}

/* breakpoints */
@media screen and (min-width: 600px) {
  nav ul {
    justify-content: space-around;
  }

  nav ul li {
    flex: 0 0 auto;
    padding: 0.7rem 1rem;
  }

  /* contact page */

  main#contact-page {
    display: block grid;
    justify-items: start;
    grid-template-areas:
      "adres contact"
      "afspraak afspraak";
  }

  main#contact-page div.adres {
    grid-area: adres;
  }

  main#contact-page div.opening {
    grid-area: contact;
  }

  main#contact-page div.afspraak {
    grid-area: afspraak;
  }

  /* contact page form met grid */

  main#contact-page div.afspraak form {
    display: block grid;
    row-gap: 20px;
    grid-template-columns: 1fr 2fr;
  }

  main#contact-page div.afspraak form > p,
  main#contact-page div.afspraak form > div {
    display: contents;
  }

  main#contact-page div.afspraak form > p > *:nth-child(1) {
    grid-column: 1;
  }
  
  main#contact-page div.afspraak form > p > *:nth-child(2) {
    grid-column: 2;
  }

  main#contact-page div.afspraak form > div > div:nth-child(1) {
    grid-column: 1;
  }
  
  main#contact-page div.afspraak form > div > div:nth-child(2) {
    grid-column: 2;
  }

  main#contact-page div.afspraak form > p:nth-last-child(1) label {
    grid-column: 1;
  }
  
  main#contact-page div.afspraak form > p:nth-last-child(2) textarea {
    grid-column: 1;
  }

}

```
